server:
  port: 8082

kafka:
  topics:
    topic-1: topic-1
    topic-2: topic-2
  bootstrap-server: "localhost:9094"

redisapp:
  url: "http://localhost:8081"
  endpoint: "/info/{clientId}"
  timeout: 5
  retries: 3
  retryDelay: 2

spring:
  data:
    redis:
      host: localhost
      port: 6380
      # password: adminpassword
      connect-timeout: 2s
      client-type: lettuce
      eventStorageTtl: 60

moderation:
  workday:
    start: "09:00"
    end: "18:00"